package dialplan;

import java.awt.event.KeyEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author oun1982
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tb_user = new javax.swing.JTextField();
        bt_submit = new javax.swing.JButton();
        bt_reset = new javax.swing.JButton();
        lb_user = new javax.swing.JLabel();
        lb_passwd = new javax.swing.JLabel();
        lb_head = new javax.swing.JLabel();
        lb_ip = new javax.swing.JLabel();
        tb_ip = new javax.swing.JTextField();
        tb_passwd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tb_user.setText(" ");
        tb_user.setCaretPosition(0);
        tb_user.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tb_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_userActionPerformed(evt);
            }
        });

        bt_submit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_submit.setText("Submit");
        bt_submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_submitMouseClicked(evt);
            }
        });
        bt_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_submitActionPerformed(evt);
            }
        });

        bt_reset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_reset.setText("Reset");

        lb_user.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_user.setText("Username");

        lb_passwd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_passwd.setText("Password");

        lb_head.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_head.setText("Edit Asterisk DialPlan");

        lb_ip.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_ip.setText("Server IP ");

        tb_ip.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tb_ip.setForeground(new java.awt.Color(255, 0, 0));
        tb_ip.setText("192.168.1.1");
        tb_ip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_ipActionPerformed(evt);
            }
        });
        tb_ip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_ipKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lb_passwd)
                        .addComponent(lb_ip))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lb_user)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bt_submit)
                            .addGap(18, 18, 18)
                            .addComponent(bt_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tb_user, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lb_head)
                                    .addGap(12, 12, 12)))
                            .addComponent(tb_ip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tb_passwd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lb_head)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_user))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_passwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_passwd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_ip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_submit)
                    .addComponent(bt_reset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tb_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_userActionPerformed

    private void tb_ipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_ipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_ipActionPerformed

    private void bt_submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_submitMouseClicked
        String tbuser = tb_user.getText().trim();
        String tbpass = tb_passwd.getText().trim();

        //System.out.println(tbuser.getClass() + " " + tbpass.getClass());
        if(tbuser.equals("admin") && tbpass.equals("admin")){
            System.out.println(tbuser.getClass() + " " + tbpass.getClass());          
            System.out.println("Login Success");
        }
        
    
    }//GEN-LAST:event_bt_submitMouseClicked

    private void tb_ipKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_ipKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String tbuser = tb_user.getText().trim();
            String tbpass = tb_passwd.getText().trim();
            //System.out.println(tbuser.getClass() + " " + tbpass.getClass());
            if(tbuser.equals("admin") && tbpass.equals("admin")){
                System.out.println(tbuser.getClass() + " " + tbpass.getClass());          
                System.out.println("Login Success");
            }
        }
    }//GEN-LAST:event_tb_ipKeyPressed

    private void bt_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_submitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_reset;
    private javax.swing.JButton bt_submit;
    private javax.swing.JLabel lb_head;
    private javax.swing.JLabel lb_ip;
    private javax.swing.JLabel lb_passwd;
    private javax.swing.JLabel lb_user;
    private javax.swing.JTextField tb_ip;
    private javax.swing.JPasswordField tb_passwd;
    private javax.swing.JTextField tb_user;
    // End of variables declaration//GEN-END:variables
}
